name: Run_ducmagic_example

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.10"]
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install
      run: |
        sudo apt install -y -q duc
        python -m pip install --upgrade pip
        pip install .
    - name: Run example index and compare to bash-magic-find.
      run: |
        duc index /
        ducmagic index /
        ducmagic ls /
        ./test_speed.sh
        ./test_speed_bash.sh
